### GET Tasks
GET http://localhost:8000/api/tasks
Accept: application/json
Authorization: Bearer 1|pepktzgKNXcpGidr4l2s7SjGX7H0MXPSo91UQCcU40556371

### POST Task
POST http://localhost:8000/api/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|pepktzgKNXcpGidr4l2s7SjGX7H0MXPSo91UQCcU40556371

{
    "title": "Read a book",
    "description": "Finish reading the Laravel documentation.",
    "due_date": "2025-12-01",
    "is_recurring": false,
    "recurring_interval": null
}

### GET Task
GET http://localhost:8000/api/tasks/11
Accept: application/json
Authorization: Bearer 1|pepktzgKNXcpGidr4l2s7SjGX7H0MXPSo91UQCcU40556371

### PATCH Task
PATCH http://localhost:8000/api/tasks/11
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|pepktzgKNXcpGidr4l2s7SjGX7H0MXPSo91UQCcU40556371

{
    "title": "Read a book - Updated",
    "description": "Continue reading the Laravel documentation.",
    "due_date": "2025-12-01",
    "is_recurring": true,
    "recurring_interval": "weekly"
}

### PATCH Status of Task
PATCH http://localhost:8000/api/tasks/11/status
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|pepktzgKNXcpGidr4l2s7SjGX7H0MXPSo91UQCcU40556371

{
    "status": "completed"
}

### DELETE Task
DELETE http://localhost:8000/api/tasks/11
Accept: application/json
Authorization: Bearer 1|pepktzgKNXcpGidr4l2s7SjGX7H0MXPSo91UQCcU40556371

### GET Tasks With Filter
GET http://localhost:8000/api/tasks?due_date_from=2020-01-01&due_date_to=2025-12-12
Accept: application/json
Authorization: Bearer 1|pepktzgKNXcpGidr4l2s7SjGX7H0MXPSo91UQCcU40556371
